from __future__ import annotations

from enum import StrEnum


class Plan(StrEnum):
    starter = "starter"
    growth = "growth"
    agency = "agency"


class Role(StrEnum):
    owner = "owner"
    admin = "admin"
    member = "member"


class Channel(StrEnum):
    google = "google"
    gsc = "gsc"
    gmb = "gmb"
    youtube = "youtube"
    instagram = "instagram"
    facebook = "facebook"
    tiktok = "tiktok"
    x = "x"
    linkedin = "linkedin"
    pinterest = "pinterest"
    snapchat = "snapchat"
    reddit = "reddit"
    whatsapp = "whatsapp"
    telegram = "telegram"
    line = "line"
    kakao = "kakao"
    vk = "vk"
    yandex = "yandex"
    naver = "naver"
    amazon = "amazon"


class AdsNetwork(StrEnum):
    google_ads = "google_ads"
    meta_ads = "meta_ads"
    tiktok_ads = "tiktok_ads"
    x_ads = "x_ads"
    linkedin_ads = "linkedin_ads"
    pinterest_ads = "pinterest_ads"
    snap_ads = "snap_ads"
    reddit_ads = "reddit_ads"
    microsoft_ads = "microsoft_ads"
    spotify_ads = "spotify_ads"
    taboola = "taboola"
    outbrain = "outbrain"
    amazon_ads = "amazon_ads"
    yandex_direct = "yandex_direct"
    kakao_moment = "kakao_moment"
    line_ads = "line_ads"


class AssetType(StrEnum):
    product = "product"
    video = "video"
    page = "page"
    post = "post"
    creative = "creative"


class AssetStatus(StrEnum):
    pending = "pending"
    processing = "processing"
    ready = "ready"
    failed = "failed"
    in_review = "in_review"
    changes_requested = "changes_requested"
    approved = "approved"


class PolicyStatus(StrEnum):
    pending = "pending"
    passed = "passed"
    blocked = "blocked"


class CampaignObjective(StrEnum):
    awareness = "awareness"
    traffic = "traffic"
    leads = "leads"
    conversions = "conversions"
    app_installs = "app_installs"
    video_views = "video_views"


class CampaignStatus(StrEnum):
    draft = "draft"
    active = "active"
    paused = "paused"
    ended = "ended"
    in_review = "in_review"
    changes_requested = "changes_requested"
    approved = "approved"
    rejected = "rejected"


class ConnectionStatus(StrEnum):
    pending = "pending"
    active = "active"
    expired = "expired"
    revoked = "revoked"


class Actor(StrEnum):
    user = "user"
    system = "system"
    ai = "ai"


class BillingProvider(StrEnum):
    razorpay = "razorpay"
    stripe = "stripe"


class BillingStatus(StrEnum):
    active = "active"
    past_due = "past_due"
    canceled = "canceled"
    trialing = "trialing"


class CreativeType(StrEnum):
    copy = "copy"
    image = "image"
    video = "video"
    thumbnail = "thumbnail"


# ─── Business Knowledge Hub ─────────────────────────────────────────────────


class KnowledgeLevel(StrEnum):
    """Four levels of business knowledge."""
    brand = "brand"            # Level 1: Brand guidelines, logo, colours, tone, mission, pricing
    business = "business"      # Level 2: SOPs, sales process, FAQs, personas, team structure
    marketing = "marketing"    # Level 3: Previous campaigns, creatives, landing pages, blogs, videos
    live = "live"              # Level 4: GA4, Shopify, HubSpot, ad platforms — continuously updated


class KnowledgeSourceStatus(StrEnum):
    """Processing status of a knowledge source."""
    pending = "pending"
    processing = "processing"
    ready = "ready"
    failed = "failed"
    expired = "expired"


class KnowledgeSourceType(StrEnum):
    """Where the knowledge document came from."""
    upload = "upload"            # User-uploaded file
    url = "url"                  # Scraped from a URL
    integration = "integration"  # Pulled from a connected integration (GA4, Shopify, etc.)
    generated = "generated"      # Generated by PRACHAR AI
    manual = "manual"            # Manually entered text


class KnowledgeFileType(StrEnum):
    """Supported file types for document processing."""
    pdf = "pdf"
    word = "word"
    excel = "excel"
    powerpoint = "powerpoint"
    csv = "csv"
    image = "image"          # OCR processed
    text = "text"
    html = "html"
    json = "json"
    url = "url"              # Website URL
    youtube = "youtube"      # YouTube transcript
